services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: priyhotel-app:latest
    container_name: priyhotel-app
    restart: unless-stopped

    environment:
      PORT: 8080

      # Aiven MySQL
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_DB_NAME: ${MYSQL_DB_NAME}
      MYSQL_USERNAME: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

      RAZORPAY_KEY: ${RAZORPAY_KEY}
      RAZORPAY_SECRET: ${RAZORPAY_SECRET}

      SMTP_HOST: ${SMTP_HOST:-smtp.gmail.com}
      SMTP_PORT: ${SMTP_PORT:-587}
      SMTP_EMAIL: ${SMTP_EMAIL}
      SMTP_PASS: ${SMTP_PASS}
      SENDTO_EMAIL: ${SENDTO_EMAIL}

      JAVA_TOOL_OPTIONS: "-XX:MaxRAMPercentage=70"

    ports:
      - "${APP_PORT:-8080}:8080"

    volumes:
      - uploads-data:/app/uploads

volumes:
  uploads-data:
